### PR TITLE
Added getter for Result context.

### PR DESCRIPTION
**Pull request by jmiazga**

### CODE REVIEW

**Comment by rawls238** [comment]
thanks!

**Comment by jmiazga** [comment]
Thanks! How long until this gets into Maven?

**Comment by rawls238** [comment]
hopefully not long, I ran into some issues deploying the latest version earlier but hopefully will have some time if not this weekend then by next week to resolve them.

**Comment by rawls238** [comment]
@jmiazga should be on maven now! Thanks for the contribution!

**Pull request merged**
