### PR TITLE
Replacing supplier with callable

### PR DESCRIPTION
**Pull request by RashmiRam**
Since there is a signature change, there is a need for bumping the version too. will have to check with @rawls238 about this.

### CODE REVIEW

**Comment by RashmiRam** [comment]
#32

**Comment by rawls238** [comment]
two things.
(1) Can you bump the version to 0.7?
(2) Any idea why the tests are failing on travis?

**Comment by RashmiRam** [comment]
I ran the tests successfully in local. 
This is the error that this is shown in travis build. I am not sure why though. Perhaps, some configuration change in travis build config? @rawls238 Can you please help me?

`$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-10-16
Expected feature release number in range of 9 to 14, but got: 8
[31;1mThe command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .[0m

Your build has been stopped.`

**Comment by RashmiRam** [comment]
@rawls238  Seems like oraclejdk-8 is failing in travis recently. Source: https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365/3
They suggested to either add `dist: trusty` in .travis.yml file or use openjdk8.

**Comment by rawls238** [comment]
thanks! I'll try to update this on maven sometime in the next couple weeks

**Comment by rawls238** [comment]
@RashmiRam this should be on maven now

**Pull request merged**
